### ISSUE TITLE
IDs for dropped things?

### ISSUE THREAD

**Issue by WhitePhant0m** [AeonLucid/GunfireRebornMods#3]
~~I was wondering how you found out the ids for the dropped things(money/essence/etc.), since I want to add XP from Spiritual Assault(new gamemode) to the list of things with infinite pickup range, and I haven't managed to figure out the id for it.~~

~~I've tried poking around the unhollowed DLLs with dnSpy but didn't find anything with it, also tried unity explorer which also yielded no results.~~

nvm, I found it, it was your debug script :P

Should've looked at that first.

**Comment by AeonLucid** [comment]
Feel free to send a PR with your update for the new gamemode 😄
